### ISSUE TITLE
Autogenerate Password when adding new Users

### ISSUE THREAD

**Issue by LokiLokus** [myOmikron/bnv-verwaltung#3]
Working with JVerein & BNV Manager is really a pain when adding new Users.
At the moment, i have to generate a Password with a Password Manager (e.g. Bitwarden), C&P it into the BNV Manager & C&P it in the JVerein Management UI.
Adding a "Generate Password" Button next to the Initial Password field and automatically add the generated Password to the clipboard would make the User Creation Process so much easier.

**Comment by WebFreak001** [comment]
this is already implemented in this version of bnv-manager:

![image](https://user-images.githubusercontent.com/2035977/209449280-8a70309b-90b9-4541-9981-aed351a8639a.png)
